package com.goku.sso.model;

public class SsoAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_auth.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_auth.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_auth.system_id
     *
     * @mbg.generated
     */
    private String systemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_auth.id
     *
     * @return the value of sso_auth.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_auth.id
     *
     * @param id the value for sso_auth.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_auth.user_id
     *
     * @return the value of sso_auth.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_auth.user_id
     *
     * @param userId the value for sso_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_auth.system_id
     *
     * @return the value of sso_auth.system_id
     *
     * @mbg.generated
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_auth.system_id
     *
     * @param systemId the value for sso_auth.system_id
     *
     * @mbg.generated
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }
}