package com.goku.sso.model;

import java.util.Date;

public class SsoUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.sso_code
     *
     * @mbg.generated
     */
    private String ssoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.last_login_system_id
     *
     * @mbg.generated
     */
    private String lastLoginSystemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.last_login_ip
     *
     * @mbg.generated
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_user.last_login_date
     *
     * @mbg.generated
     */
    private Date lastLoginDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.id
     *
     * @return the value of sso_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.id
     *
     * @param id the value for sso_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.sso_code
     *
     * @return the value of sso_user.sso_code
     *
     * @mbg.generated
     */
    public String getSsoCode() {
        return ssoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.sso_code
     *
     * @param ssoCode the value for sso_user.sso_code
     *
     * @mbg.generated
     */
    public void setSsoCode(String ssoCode) {
        this.ssoCode = ssoCode == null ? null : ssoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.user_name
     *
     * @return the value of sso_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.user_name
     *
     * @param userName the value for sso_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.password
     *
     * @return the value of sso_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.password
     *
     * @param password the value for sso_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.status
     *
     * @return the value of sso_user.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.status
     *
     * @param status the value for sso_user.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.email
     *
     * @return the value of sso_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.email
     *
     * @param email the value for sso_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.idcard
     *
     * @return the value of sso_user.idcard
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.idcard
     *
     * @param idcard the value for sso_user.idcard
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.mobile
     *
     * @return the value of sso_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.mobile
     *
     * @param mobile the value for sso_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.last_login_system_id
     *
     * @return the value of sso_user.last_login_system_id
     *
     * @mbg.generated
     */
    public String getLastLoginSystemId() {
        return lastLoginSystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.last_login_system_id
     *
     * @param lastLoginSystemId the value for sso_user.last_login_system_id
     *
     * @mbg.generated
     */
    public void setLastLoginSystemId(String lastLoginSystemId) {
        this.lastLoginSystemId = lastLoginSystemId == null ? null : lastLoginSystemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.last_login_ip
     *
     * @return the value of sso_user.last_login_ip
     *
     * @mbg.generated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.last_login_ip
     *
     * @param lastLoginIp the value for sso_user.last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_user.last_login_date
     *
     * @return the value of sso_user.last_login_date
     *
     * @mbg.generated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_user.last_login_date
     *
     * @param lastLoginDate the value for sso_user.last_login_date
     *
     * @mbg.generated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }
}