package com.goku.sso.model;

public class SsoSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.Id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.index_url
     *
     * @mbg.generated
     */
    private String indexUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.login_url
     *
     * @mbg.generated
     */
    private String loginUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sso_system.if_show
     *
     * @mbg.generated
     */
    private String ifShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.Id
     *
     * @return the value of sso_system.Id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.Id
     *
     * @param id the value for sso_system.Id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.code
     *
     * @return the value of sso_system.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.code
     *
     * @param code the value for sso_system.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.name
     *
     * @return the value of sso_system.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.name
     *
     * @param name the value for sso_system.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.url
     *
     * @return the value of sso_system.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.url
     *
     * @param url the value for sso_system.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.index_url
     *
     * @return the value of sso_system.index_url
     *
     * @mbg.generated
     */
    public String getIndexUrl() {
        return indexUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.index_url
     *
     * @param indexUrl the value for sso_system.index_url
     *
     * @mbg.generated
     */
    public void setIndexUrl(String indexUrl) {
        this.indexUrl = indexUrl == null ? null : indexUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.login_url
     *
     * @return the value of sso_system.login_url
     *
     * @mbg.generated
     */
    public String getLoginUrl() {
        return loginUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.login_url
     *
     * @param loginUrl the value for sso_system.login_url
     *
     * @mbg.generated
     */
    public void setLoginUrl(String loginUrl) {
        this.loginUrl = loginUrl == null ? null : loginUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.description
     *
     * @return the value of sso_system.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.description
     *
     * @param description the value for sso_system.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sso_system.if_show
     *
     * @return the value of sso_system.if_show
     *
     * @mbg.generated
     */
    public String getIfShow() {
        return ifShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sso_system.if_show
     *
     * @param ifShow the value for sso_system.if_show
     *
     * @mbg.generated
     */
    public void setIfShow(String ifShow) {
        this.ifShow = ifShow == null ? null : ifShow.trim();
    }
}