package com.goku.sso.mapper;

import com.goku.sso.model.SsoSystem;

public interface SsoSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_system
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_system
     *
     * @mbg.generated
     */
    int insert(SsoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_system
     *
     * @mbg.generated
     */
    int insertSelective(SsoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_system
     *
     * @mbg.generated
     */
    SsoSystem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SsoSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_system
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SsoSystem record);
}