package com.goku.sso.mapper;

import com.goku.sso.model.SsoUser;

public interface SsoUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    int insert(SsoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    int insertSelective(SsoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    SsoUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SsoUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SsoUser record);
}