package com.goku.sso.mapper;

import com.goku.sso.model.SsoAuth;

public interface SsoAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_auth
     *
     * @mbg.generated
     */
    int insert(SsoAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_auth
     *
     * @mbg.generated
     */
    int insertSelective(SsoAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_auth
     *
     * @mbg.generated
     */
    SsoAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SsoAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SsoAuth record);
}