package com.goku.sso.mapper;

import com.goku.sso.model.SsoLog;

public interface SsoLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_log
     *
     * @mbg.generated
     */
    int insert(SsoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_log
     *
     * @mbg.generated
     */
    int insertSelective(SsoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_log
     *
     * @mbg.generated
     */
    SsoLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SsoLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sso_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SsoLog record);
}